
networks:
  lamp-docker-network:
    driver: bridge
services:
  postgres:
    image: postgres:14.1-alpine
    restart: 'always'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '54320:5432'
    networks:
      - lamp-docker-network
  www.garry.com:
    depends_on:
      - postgres
    build: 
      context: .
    container_name: 'www.garry.com'
    restart: 'always'
    ports:
      - 80:80
      - 443:443
    networks:
      - lamp-docker-network

